[package]
name="rsa_sample"
type="bin"
authors = ["saleel"]
compiler_version = ">=0.38.0"

[dependencies]
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.4.1" }
rsa = { git = "https://github.com/noir-lang/noir_rsa", tag = "v0.4.0", directory="lib" }
string_search = { git = "https://github.com/noir-lang/noir_string_search", tag = "v0.3.0" }
