[package]
name="rsa_sample"
type="bin"
authors = ["saleel"]
compiler_version = ">=0.38.0"

[dependencies]
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.6.0" }
rsa = { git = "https://github.com/noir-lang/noir_rsa", tag = "v0.7.0" }
string_search = { git = "https://github.com/noir-lang/noir_string_search", tag = "v0.3.2" }
sha256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/sha256" }
